name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Node.js dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest

    needs: setup
    if: success()

    steps:
      - name: Run tests
        run: npm test
        working-directory: ./testCICD

  build:
    runs-on: ubuntu-latest

    needs: setup
    if: success()

    steps:
      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod --dir=./build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
