name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Node.js dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
      
        # Add deployment steps here
      # Example: Deploy to Netlify
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod --dir=./build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  